// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShthpeUR0TY2pKR4kzEMfMHQW8T98hrg',
    appId: '1:361846858228:web:0b40ed7bb2365b6a9159a1',
    messagingSenderId: '361846858228',
    projectId: 'urbancoll-89617707-90dc8',
    authDomain: 'urbancoll-89617707-90dc8.firebaseapp.com',
    storageBucket: 'urbancoll-89617707-90dc8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzRKw7dVw1og7IBe-Ftnsm1GMuykprGyE',
    appId: '1:361846858228:ios:5d44909b8dcd7de29159a1',
    messagingSenderId: '361846858228',
    projectId: 'urbancoll-89617707-90dc8',
    storageBucket: 'urbancoll-89617707-90dc8.firebasestorage.app',
    iosBundleId: 'com.example.urbancoll',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRKw7dVw1og7IBe-Ftnsm1GMuykprGyE',
    appId: '1:361846858228:ios:5d44909b8dcd7de29159a1',
    messagingSenderId: '361846858228',
    projectId: 'urbancoll-89617707-90dc8',
    storageBucket: 'urbancoll-89617707-90dc8.firebasestorage.app',
    iosBundleId: 'com.example.urbancoll',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQNN549rlgj_ZL4es9QPrGPKpUGTYgHY',
    appId: '1:361846858228:android:f3486f23894c61269159a1',
    messagingSenderId: '361846858228',
    projectId: 'urbancoll-89617707-90dc8',
    storageBucket: 'urbancoll-89617707-90dc8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBShthpeUR0TY2pKR4kzEMfMHQW8T98hrg',
    appId: '1:361846858228:web:ca40dc1ef5ce31e39159a1',
    messagingSenderId: '361846858228',
    projectId: 'urbancoll-89617707-90dc8',
    authDomain: 'urbancoll-89617707-90dc8.firebaseapp.com',
    storageBucket: 'urbancoll-89617707-90dc8.firebasestorage.app',
  );

}